[package]
name = "aoc_2022_rust"
version = "0.1.0"
edition = "2021"
default-run = "aoc_2022_rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_lib = { path = "lib" }
regex = "1"
