[package]
name = "aoc-2021-rust"
version = "0.1.0"
edition = "2021"
default-run = "aoc-2021-rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
